%% Sanity Check
% Run all the functions that will be checked to make sure
% all required functions and returned variables exist
clear all; close all ; clc ;

functions_list = {...
    'H = trans_func( 75e6 , 10e6 , 50) ;',...
    'syms f ; H2(f)=f ; plot_H( H2 , 75e6 , 50e6 )  ;',...
    'close all ;',...
    'BW = find_BW( H , 100 ) ;',...
    '[arrival_times , service_times] = generate_arrival_service_times(1.5 , 2) ;',...    
    '[finish_times , drop_times] = sim_queue( cumsum(rand(25000,1)) , rand(25000,1) , 13 ) ;',...        
    'ID = getID() ;'...    
    } ;

for function_index = 1 : numel(functions_list)
    string = functions_list{function_index} ;
    try
        eval(string) ;
    catch
        h = msgbox({'Error: A problem occurred while calling to:',...
            string ,...
            'Please fix the problem and try again.'},...
            'A Message For You...') ;
        set(h,'Color','r') ;
        return ;
    end
    
end
h = msgbox('All functions were successfully called!',...
    'A Message For You...') ;
set(h,'Color','g') ;