%% Sanity Check
% Run all the functions that will be checked to make sure
% all required functions and returned variables exist
clear; close all ; clc ;

functions_list = {...
    'coefs = a_n_coefs(5) ;',...
    's_n_vals = s_n(4 , 1 , [-0.1 , 0.1 , 0.3] ) ;',...
    'plot_s_n( 5 , 2 , 1 ) ;',...
    'close all ;',...
    'coefs_mat = r_n_coefs( 3 , 1 , 1 , 1 ) ;',...
    'y_n_vals = y_n( 4 , 1 , 1 , 1 , [-0.45 , 0.3 , -0.4] ) ;',...    
    'plot_y_50( 0.1 , 1 , 20 ) ;',...        
    'close all ;',...
    'tone = single_dtmf( num2str(6) , 200) ;',...            
    'dial_vec = atdt( num2str(12345) ) ;',...                
    'close all ;',...
    'samples = find_ring_intervals( [0 0 -1 2 -4 0 3 0 0 0 5 -1 -4 0 2 3 0 0 0 0 0] ) ;',...
    'ID = getID() ;'...    
    } ;

for function_index = 1 : numel(functions_list)
    string = functions_list{function_index} ;
    try
        eval(string) ;
    catch
        h = msgbox({'Error: A problem occurred while calling to:',...
            string ,...
            'Please fix the problem and try again.'},...
            'A Message For You...') ;
        set(h,'Color','r') ;
        return ;
    end
    
end
h = msgbox('All functions were successfully called!',...
    'A Message For You...') ;
set(h,'Color','g') ;